# Copyright 2019 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

def log(*args):
  print("[[toolchains/local/index.bzl]]", *args)

def _pyenv_impl(repository_ctx):
  if repository_ctx.os.name.find("windows") != -1:
    fail("Windows OS is not supported on this moment")

  versions = repository_ctx.attr.versions
  log("_pyenv_impl", versions)
  for version in versions:
    log(version)
    repository_ctx.file("pyenv/BUILD", """
# Generated by toolchains/index.bzl
package(default_visibility = ["//visibility:public"])
alias(
  name = "{}",
  actual = "bin/python"
)
""".format(version)
                    )
  result = repository_ctx.execute([
      "pwd"
      ], quiet=False)
  log("_pyenv_impl1")
  log(result.stdout)
  pass

def _impl(repository_ctx):
  print(">> repository_ctx", repository_ctx)

  repository_ctx.file("BUILD", "")
  repository_ctx.file("WORKSPACE", "")
  return
  repository_ctx.download({
    'url': 'https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz'
  })
  print("repository_ctx", repository_ctx)
  fail
  print(repository_ctx.attr)

py_toolchain = repository_rule(
  implementation = _impl,
  attrs = {
    'local': attr.bool(),
    'versions': attr.string_list(mandatory=True)
  }
)
